"""The startup banner, painted in this session's colours.

WHY THIS IS SEPARATE FROM THE PALETTE

The banner ASCII art does NOT read the colour keys. `hermes_cli/banner.py:60`
hardcodes a gold gradient into the Rich markup itself — `[bold #FFD700]`,
`[#FFBF00]`, `[#CD7F32]` — so a skin can set all 23 colour keys correctly and the
biggest thing on the screen stays stock gold. Measured on Chef: after the palette
fix the terminal painted our greens AND still painted #FFD700/#CD7F32/#FFBF00,
all of it from the logo and the caduceus.

The escape hatch is `banner_logo` / `banner_hero` in the skin: whole-string
overrides that `banner.py:916` prefers over the built-in art. So we generate both
per session, in the session's own hues.

WHAT WE DRAW

The hero image (`banner_hero`) is generated by `mantle.py` — the session's own
chromatophore pattern, sized to the caduceus slot it replaces. This module owns
only the wordmark.

The wordmark keeps Hermes' letterforms (this is a Hermes theme, not a rebrand)
but takes a three-stop gradient down the identity hue, mirroring how the real
gradient runs light-to-dark.
"""

from __future__ import annotations

from .color.oklab import OKLCh, hex_to_oklch, oklch_to_hex

__all__ = ["banner_logo"]


# Hermes' own letterforms, with the colour stripped out so we can re-ink them.
# Kept verbatim from hermes_cli/banner.py so the wordmark stays recognisably
# Hermes — we are theming it, not replacing the product's identity.
_LOGO_ROWS = (
    "██╗  ██╗███████╗██████╗ ███╗   ███╗███████╗███████╗       █████╗  ██████╗ ███████╗███╗   ██╗████████╗",
    "██║  ██║██╔════╝██╔══██╗████╗ ████║██╔════╝██╔════╝      ██╔══██╗██╔════╝ ██╔════╝████╗  ██║╚══██╔══╝",
    "███████║█████╗  ██████╔╝██╔████╔██║█████╗  ███████╗█████╗███████║██║  ███╗█████╗  ██╔██╗ ██║   ██║",
    "██╔══██║██╔══╝  ██╔══██╗██║╚██╔╝██║██╔══╝  ╚════██║╚════╝██╔══██║██║   ██║██╔══╝  ██║╚██╗██║   ██║",
    "██║  ██║███████╗██║  ██║██║ ╚═╝ ██║███████╗███████║      ██║  ██║╚██████╔╝███████╗██║ ╚████║   ██║",
    "╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝      ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝   ╚═╝",
)


def _ramp(identity: OKLCh, rows: int) -> list[str]:
    """A light-to-dark ramp down the identity hue.

    Mirrors the direction of Hermes' own gold gradient (bright at the top,
    bronze at the bottom) so the banner keeps its familiar shape while changing
    its colour. Chroma rises slightly as lightness falls, because sRGB holds more
    chroma at lower L — the same constraint that governs the accent colours.
    """
    out = []
    for i in range(rows):
        t = i / max(1, rows - 1)
        L = 0.80 - 0.26 * t
        C = min(0.24, identity.C * (1.05 + 0.35 * t))
        out.append(oklch_to_hex(OKLCh(L, C, identity.h)))
    return out


def banner_logo(identity_hex: str) -> str:
    """The Hermes wordmark, inked in this session's hue. Rich markup."""
    identity = hex_to_oklch(identity_hex)
    ramp = _ramp(identity, len(_LOGO_ROWS))
    lines = []
    for i, row in enumerate(_LOGO_ROWS):
        bold = "bold " if i < 2 else ""
        lines.append(f"[{bold}{ramp[i]}]{row}[/]")
    return "\n".join(lines)
